# הגדרות למסד נתונים מקומי בזיכרון (H2)
spring.datasource.url=jdbc:h2:mem:quizdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# הגדרות Hibernate - הוא יצור את הטבלאות לבד כל פעם מחדש
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# פתיחת ממשק ניהול בכתובת localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# הגדרה שמאפשרת לראות את הקונסול בתוך דפדפן
spring.h2.console.settings.web-allow-others=true

# הגדרות התחברות גוגל
spring.security.oauth2.client.registration.google.client-id=921674908244-t48n1740ou48dip9potbrsnlslpshi7p.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile