# מאפשר את ממשק הניהול של מסד הנתונים
spring.h2.console.enabled=true
# הכתובת שדרכה ניכנס
spring.h2.console.path=/h2-console
# הגדרת מסד הנתונים בזיכרון
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# מציג את השאילתות שה-JPA מריץ ב-Console (מאוד עוזר לדיבאג!)
spring.jpa.show-sql=true
# יוצר את הטבלאות מחדש בכל הפעלה לפי ה-Entities
spring.jpa.hibernate.ddl-auto=update