# הגדרות למסד נתונים מקומי בזיכרון (H2)
spring.datasource.url=jdbc:h2:mem:quizdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# הגדרות Hibernate - הוא יצור את הטבלאות לבד כל פעם מחדש
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# פתיחת ממשק ניהול בכתובת localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# הגדרה שמאפשרת לראות את הקונסול בתוך דפדפן
spring.h2.console.settings.web-allow-others=true

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=921674908244-t48n1740ou48dip9potbrsnlslpshi7p.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# מחרוזת החיבור המעודכנת עם כל התיקונים
#spring.datasource.url=jdbc:postgresql://db.ufasfvklhalihfzrgirs.supabase.co:5432/postgres

## שם משתמש וסיסמה (השתמשי בסיסמה שהגדרת כשפתחת את הפרויקט ב-Supabase)
#spring.datasource.username=postgres
#spring.datasource.password=p?8pqQ,ixfVv7x9
#
## טיפול במרחק הגיאוגרפי (סינגפור) ובסינון
#spring.datasource.hikari.connection-timeout=60000
#spring.datasource.hikari.maximum-pool-size=5
#
## הגדרה ידנית של הדיאלקט כדי למנוע את שגיאת ה-Metadata
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring.datasource.url=jdbc:postgresql://db.ufasfvklhalihfzrgirs.supabase.co:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=p?8pqQ,ixfVv7x9
#spring.datasource.driver-class-name=org.postgresql.Driver